spring.application.name=warehouse-service
server.port=8083

#  MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/stockpro_warehouse_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ravi@ku123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.forward-headers-strategy=framework
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#  Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}

# Redis Cache
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

#  JWT
jwt.secret=mysecretkeymysecretkeymysecretkey12345
jwt.expiration=28800000

#  Logging
logging.level.org.springframework=INFO
logging.level.com.stockpro=DEBUG

#  Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ℹ Info
info.app.name=Warehouse Service
info.app.version=1.0
info.app.description=Inventory Product Microservice

# RabbitMQ Config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


# Logging — SLF4J log file
logging.file.name=logs/stockpro-warehouse.log
logging.level.root=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
