spring.application.name=eureka-service


server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Logging — SLF4J log file
logging.file.name=logs/stockpro-eureka.log
logging.level.root=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n